"""Sync discovered models into DeerFlow's config.yaml.

Usage:
    export NVIDIA_API_KEY=nvapi-... ZAI_API_KEY=...
    python -m providers.sync                    # prints the models: YAML section
    python -m providers.sync --write config.yaml # merges into config.yaml

Run it whenever you want DeerFlow's UI/model picker to show the latest
catalog (e.g. after NVIDIA launches new models). The router itself discovers
models live at runtime; this tool only exists to feed DeerFlow's static
config file.
"""

from __future__ import annotations

import argparse
import os
import sys

from .discovery import ModelCatalog, NVIDIA_BASE_URL, ZAI_BASE_URL
from .ranker import rank_models

HEADER = (
    "# ---- Generated by providers.sync (DeerFlow evolved 2.5) ----\n"
    "# Auto-discovered live from NVIDIA NIM and z.ai. Re-run after providers\n"
    "# launch new models: python -m providers.sync --write config.yaml\n"
)


def entry_to_yaml(idx: int, e) -> str:
    name = e.model.split("/")[-1].replace(".", "-").replace("_", "-")
    return f"""  - name: {name}
    display_name: {e.model} ({e.provider})
    use: langchain_openai:ChatOpenAI
    model: {e.model}
    api_base: {e.api_base}
    api_key: ${e.api_key_env}
    timeout: 600.0
    max_retries: 2
    request_admission:
      requests_per_minute: 40
"""


def generate_section(nvidia_depth: int = 4) -> str:
    catalog = ModelCatalog()
    entries = catalog.discover()
    if not entries:
        sys.exit("No models discovered — check NVIDIA_API_KEY / ZAI_API_KEY.")
    ranked = rank_models(entries)
    nvidia = [e for e in ranked if e.provider == "nvidia"][:nvidia_depth]
    zai = [e for e in ranked if e.provider == "zai"]
    lines = [HEADER, "models:"]
    for e in nvidia + zai:
        lines.append(entry_to_yaml(len(lines), e).rstrip("\n"))
    return "\n".join(lines) + "\n"


def merge_into_config(config_path: str, section: str) -> None:
    """Replace (or insert) the `models:` section inside config.yaml."""
    if not os.path.exists(config_path):
        with open(config_path, "w", encoding="utf-8") as fh:
            fh.write(section)
        return

    with open(config_path, "r", encoding="utf-8") as fh:
        lines = fh.readlines()

    out, i, replaced = [], 0, False
    while i < len(lines):
        if lines[i].rstrip("\n") == "models:":
            replaced = True
            # skip the whole existing models block (2-space indented entries)
            i += 1
            while i < len(lines) and (lines[i].startswith("  ") or lines[i].strip() == ""):
                if lines[i].strip() == "" and i + 1 < len(lines) and lines[i + 1].startswith("  "):
                    i += 1
                    continue
                if lines[i].startswith("  "):
                    i += 1
                    continue
                break
            out.append(section)
        else:
            out.append(lines[i])
            i += 1
    if not replaced:
        out.append("\n" + section)

    with open(config_path, "w", encoding="utf-8") as fh:
        fh.writelines(out)


def main() -> None:
    ap = argparse.ArgumentParser(description="Sync provider models into DeerFlow config")
    ap.add_argument("--write", metavar="CONFIG", help="merge into this config.yaml path")
    ap.add_argument("--depth", type=int, default=4, help="top N NVIDIA models (default 4)")
    args = ap.parse_args()

    section = generate_section(nvidia_depth=args.depth)
    if args.write:
        merge_into_config(args.write, section)
        print(f"Updated {args.write}")
    else:
        print(section)


if __name__ == "__main__":
    main()
